name: Java CI with Gradle

on:
  push:
    branches: [ "code" ]
  pull_request:
    branches: [ "code" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # Downgrade to JDK 11 for compatibility
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Set up Gradle with version 7.5 or newer
    - name: Setup Gradle 7.x
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.5'

    # Clean Gradle cache to avoid corruption
    - name: Clean Gradle Cache
      run: |
        rm -rf ~/.gradle/caches/
        rm -rf ~/.gradle/scripts-remapped/

    # Build the project with detailed debugging info
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build --debug --stacktrace

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Submit dependency graph for security alerts
    - name: Generate and submit dependency graph
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'dependencies'
