name: Java CI with Gradle

on:
  push:
    branches: [ "code" ]
  pull_request:
    branches: [ "code" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 11 (or change to JDK 17 if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Set up Gradle with caching and specify a newer Gradle version (e.g., 7.5)
    - name: Setup Gradle 7.x
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.5'

    # Clean the entire Gradle cache and remapped scripts to avoid cache corruption
    - name: Clean Gradle Cache
      run: |
        rm -rf ~/.gradle/caches/
        rm -rf ~/.gradle/scripts-remapped/

    # Build the project using the Gradle Wrapper with detailed info
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build --info --stacktrace

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Submit dependency graph for security alerts and analysis
    - name: Generate and submit dependency graph
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'dependencies'
